config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :userimages
  root 'userimages#my_userimages'
  get "/my_userimages" => "userimages#my_userimages", as: :my_userimages
  get "/share_to_me " => "userimages#sharetome", as: :sharetome
  get "/applyfilter/:type" => "userimages#applyfilter", as: :applyfilter
  get "/share" => "userimages#shareimage", as: :share
  get "/download/:image" => "userimages#download", as: :download
  get "/trash" => "userimages#trash", as: :trash
  get "/remove/:image" => "userimages#remove", as: :remove
  get "/restore/:image" => "userimages#restore", as: :restore
  get "/saveimage/:id" => "userimages#saveimage"
  get "/cancelshare/:imageid" => "userimages#cancelshare", as: :cancelshare

end

app/models/userimage.rb
class Userimage < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/controllers/userimages_controller.rb
require 'RMagick'

class UserimagesController < ApplicationController
  before_action :set_userimage, only: [:show, :edit, :update, :destroy, :applyfilter, :shareimage]
  respond_to :js, :html

  def applyfilter
    @type = params[:type]
    filter = ImageFilter.new("public" + @userimage.image_url.to_s, "preview")
    @image_blob = filter.bubble if (@type == "bubble")
    @image_blob = filter.water_mark if (@type == "water_mark")
    @image_blob = filter.raise if (@type == "raise")
    @image_blob = filter.stamp if (@type == "stamp")
    @image_blob = filter.radial if (@type == "radial")
    @image_blob = filter.ink if (@type == "ink")
    @image_blob = filter.roll if (@type == "roll")
    @image_blob = filter.sketch if (@type == "sketch")
    @image_blob = filter.spread if (@type == "spread")
    @image_blob = filter.vignette if (@type == "vignette")
    @image_blob = filter.shade if (@type == "shade")
    @image_blob = filter.wave if (@type == "wave")
  end

  def shareimage
    shareemail = params[:email]
    imageid = params[:id]
    @share = Sharelist.new()
    @share.email = shareemail
    @share.imageid = imageid
    @share.save
    respond_to do |format|
      if @share.save
        format.html { redirect_to :back, notice: 'Image was successfully shared.' }
      else
        format.html { redirect_to :back, notice: 'Shared fail!' }
      end
    end
  end

  def cancelshare
    imageid = params[:imageid]
    shares = Sharelist.where(imageid: imageid)
    shares.first.destroy
    @shareimages ||= []
    @shares = Sharelist.where(email: current_user.email)
    @shares.each { |share|
      @userimage = Userimage.find(share.imageid)
      @shareimages << @userimage
    }
    render action: "sharetome"
  end

  def sharetome
    @shareimages ||= []
    @shares = Sharelist.where(email: current_user.email)
    @shares.each { |share|
      @userimages = Userimage.where(id: share.imageid)
      @shareimages << @userimages.first()
    }
  end

  def trash
    @userimages = Userimage.where(user_id: current_user.id).where(is_delete: 1)
  end

  def download
    image = Userimage.find(params[:image])
    send_file "public"+image.image.to_s
  end

  def index
    @userimages = Userimage.all
    respond_with(@userimages)
  end

  def my_userimages
    @userimages = Userimage.where(user_id: current_user.id).where(is_delete: 0)
  end

  def show
    respond_with(@userimage)
  end

  def new
    @userimage = Userimage.new
    respond_with(@userimage)
  end

  def edit
  end

  def create
    @userimage = Userimage.new(userimage_params)
    @userimage.user_id = current_user.id
    @userimage.is_delete = 0;
    respond_to do |format|
      if @userimage.save
        format.html { redirect_to my_userimages_path, notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @userimage }
      else
        format.html { render action: 'new' }
        format.json { render json: @userimage.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @userimage.update(userimage_params)
        format.html { redirect_to @userimage, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @userimage.errors, status: :unprocessable_entity }
      end
    end
  end

  def saveimage
    imageid = params[:id]
    @type = params[:filtertype]
    imageurl = params[:imageurl]
    title = params[:title]
    description = params[:description]
    userimage = Userimage.find(imageid)
    userimage.title = title
    userimage.description = description
    userimage.save #Save image info
    #Save image
    filter = ImageFilter.new("public" + imageurl, "save")
    filter.bubble if (@type == "bubble")
    filter.water_mark if (@type == "water_mark")
    filter.raise if (@type == "raise")
    filter.stamp if (@type == "stamp")
    filter.radial if (@type == "radial")
    filter.ink if (@type == "ink")
    filter.roll if (@type == "roll")
    filter.sketch if (@type == "sketch")
    filter.spread if (@type == "spread")
    filter.vignette if (@type == "vignette")
    filter.shade if (@type == "shade")
    filter.wave if (@type == "wave")
    @userimages = Userimage.where(user_id: current_user.id).where(is_delete: 0)
    render action: 'my_userimages'
  end

  def remove
    image = Userimage.find(params[:image])
    image.is_delete = 1;
    image.save
    @userimages = Userimage.where(user_id: current_user.id).where(is_delete: 0)
    render action: 'my_userimages'
  end

  def restore
    image = Userimage.find(params[:image])
    image.is_delete = 0;
    image.save
    @userimages = Userimage.where(user_id: current_user.id).where(is_delete: 1)
    render action: 'trash'
  end

  def destroy
    @userimage.destroy
    respond_to do |format|
      format.html { redirect_to "/trash" }
      format.json { head :no_content }
    end
  end

  private
  def set_userimage
    @userimage = Userimage.find(params[:id])
  end

  def userimage_params
    params.require(:userimage).permit(:title, :imageversion, :description, :image)
  end
end

app/helpers/userimages_helper.rb
module UserimagesHelper
end

app/views/userimages/_form.html.erb
<%= form_for(@userimage) do |f| %>
  <% if @userimage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userimage.errors.count, "error") %> prohibited this userimage from being saved:</h2>

      <ul>
      <% @userimage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title,class:"form-control" ,style:"width:50%"%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description,class:"form-control",style:"width:50%" %>
  </div>
  <div>
    <%= f.submit  class: "btn btn-primary" %>
    <%= link_to 'Back', my_userimages_path, class: "btn btn-default" %>
   </div>
<% end %>

app/views/userimages/applyfilter.html.erb
<div class="sidebar">
  <div class="row">
    <div class="span6">
      <ul class="nav nav-list">
        <br/>
        <li><%= link_to 'Raise', {:controller =>'userimages', :action => 'applyfilter', :type => 'raise', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Radial', {:controller =>'userimages', :action => 'applyfilter', :type => 'radial', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Ink', {:controller =>'userimages', :action => 'applyfilter', :type => 'ink', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Roll', {:controller =>'userimages', :action => 'applyfilter', :type => 'roll', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Sketch', {:controller =>'userimages', :action => 'applyfilter', :type => 'sketch', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Spread', {:controller =>'userimages', :action => 'applyfilter', :type => 'spread', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Vignette', {:controller =>'userimages', :action => 'applyfilter', :type => 'vignette', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Shade', {:controller =>'userimages', :action => 'applyfilter', :type => 'shade', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Wave', {:controller =>'userimages', :action => 'applyfilter', :type => 'wave', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Stamp', {:controller =>'userimages', :action => 'applyfilter', :type => 'stamp', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Cancel', {:controller =>'userimages', :action => 'edit', :id => @userimage}, class: "btn btn-warning" %>
        </li>
        <br/>
      </ul>
    </div>
  </div>
</div>
<div class="picture"><%= ("<img id = 'profile-image' alt = 'image' class = 'list_image' src='data:image/jpg;base64,%s'>" % Base64.encode64(@image_blob)).html_safe %>
</div>
<div class="picture">
  <br/> <br/>
  <form action="/saveimage/<%= @userimage.id %>" method="get">
    <div class="panel panel-default" style="width: 70%">
      <div class="panel-heading">Title</div>
      <div class="panel-body"><input class="form-control" type="text" name="title" value="<%=@userimage.title%>"></div>
    </div>
    <div class="panel panel-default" style="width: 70%">
      <div class="panel-heading">Description</div>
      <div class="panel-body"> <input class="form-control" type="text" name="description" value="<%=@userimage.description%>"></div>
    </div>
    <input type="hidden" name="imageurl" value="<%=@userimage.image_url.to_s%>" >
    <input type="hidden" name="filtertype" value= <%= @type %> >
    <input type="submit" class="btn btn-primary" value="Save Changes">
    <%= link_to 'Back', my_userimages_path, class: "btn btn-default" %>
  </form>
</div>

app/views/userimages/edit.html.erb
<div class="sidebar">
  <div class="row">
    <div class="span6">
      <ul class="nav nav-list">
        <br/>
        <li><%= link_to 'Raise', {:controller =>'userimages', :action => 'applyfilter', :type => 'raise', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Radial', {:controller =>'userimages', :action => 'applyfilter', :type => 'radial', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Radial', {:controller =>'userimages', :action => 'applyfilter', :type => 'radial', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Ink', {:controller =>'userimages', :action => 'applyfilter', :type => 'ink', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Roll', {:controller =>'userimages', :action => 'applyfilter', :type => 'roll', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Sketch', {:controller =>'userimages', :action => 'applyfilter', :type => 'sketch', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Spread', {:controller =>'userimages', :action => 'applyfilter', :type => 'spread', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Vignette', {:controller =>'userimages', :action => 'applyfilter', :type => 'vignette', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Shade', {:controller =>'userimages', :action => 'applyfilter', :type => 'shade', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Wave', {:controller =>'userimages', :action => 'applyfilter', :type => 'wave', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Stamp', {:controller =>'userimages', :action => 'applyfilter', :type => 'stamp', :id => @userimage}, class: "btn btn-default" %>
        </li>
        <br/>
        <li><%= link_to 'Cancel', {:controller =>'userimages', :action => 'edit', :id => @userimage}, class: "btn btn-warning" %>
        </li>
        <br/>
      </ul>
    </div>
  </div>
</div>
  <div class="picture"><%= image_tag @userimage.image_url.to_s %></div>
<div class="picture">
  <br/> <br/>
  <form action="/saveimage/<%= @userimage.id %>" method="get">
    <div class="panel panel-default" style="width: 50%">
  <div class="panel-heading">Title</div>
    <div class="panel-body"><input class="form-control" type="text" name="title" value="<%=@userimage.title%>"></div>
    </div>
    <div class="panel panel-default" style="width: 50%">
    <div class="panel-heading">Description</div>
      <div class="panel-body"> <input class="form-control" type="text" name="description" value="<%=@userimage.description%>"></div>
    </div>
  <input type="hidden" name="imageurl" value="<%=@userimage.image_url.to_s%>" >
  <input type="hidden" name="filtertype" value= <%= @type %> >
  <input type="submit" class="btn btn-primary" value="Save Changes">
  <%= link_to 'Back', my_userimages_path, class: "btn btn-default" %>
</form>
</div>

app/views/userimages/index.html.erb
<h1>Listing userimages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Imageversion</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userimages.each do |userimage| %>
      <tr>
        <td><%= userimage.title %></td>
        <td><%= userimage.imageversion %></td>
        <td><%= userimage.description %></td>
        <td><%= userimage.image %></td>
        <td><%= link_to 'Show', userimage %></td>
        <td><%= link_to 'Edit', edit_userimage_path(userimage) %></td>
        <td><%= link_to 'Destroy', userimage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userimage', new_userimage_path %>

app/views/userimages/my_userimages.html.erb
<tbody>
<h3 align="center">My Images</h3>

<p style="text-align:center" class="notice"><%= notice %></p>

<p style="text-align:center" class="alert"><%= alert %></p>
<% @userimages.each do |image| %>
    <div class="showBox">
      <div class="box">
        </br>
        <div class="panel panel-default" style="width: 85%">
          <div class="panel-heading">Title:    <%= image.title %></div>
          <div class="panel-body">
            Description:    <%= image.description %>
          </div>
        </div>

        <div><%= image_tag image.image_url(:thumb).to_s %></div>
        <% if user_signed_in? %>
            <br/>

            <form action="/share" method="get">
              Share to: <input class="form-control" style="width: 86%" type="text" name="email">
              <br/>
              <input type="hidden" name="id" value="<%= image.id %>">
              <input type="submit" class="btn btn-primary" value="Share">
              <%= link_to 'Download', download_path(image.id), class: "btn btn-primary" %>
              <%= link_to 'Edit', edit_userimage_path(image), class: "btn btn-primary" %>
              <%= link_to 'Remove', remove_path(image.id), data: {confirm: 'Image will be put in the trash, you can restore it back'}, class: "btn btn-danger" %>
            </form>
        <% end %>

      </div>
      <br/><br/>
    </div>
<% end %>
</tbody>

app/views/userimages/new.html.erb
<h1>Create a new image</h1>
<%= form_for @userimage do |f| %>
    <p>Title: <%= f.text_field :title,class:"form-control" , style:"width:50%"%></p>
    <p>Description: <%= f.text_area :description ,class:"form-control", style:"width:50%"%></p>
    <p><%= f.file_field :image, class: "btn btn-default" %></p>
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Back', my_userimages_path, class: "btn btn-default" %>
<% end %>

app/views/userimages/sharetome.html.erb
  <tbody>
  <h3 align="center">Share To Me</h3>
  <p style="text-align:center" class="notice"><%= notice %></p>
  <p style="text-align:center" class="alert"><%= alert %></p>
  <% @shareimages.each do |image| %>
      <% if image %>
          <div class="showBox">
            <div class="box">
              </br>

              <div class="panel panel-default" style="width: 85%">
                <div class="panel-heading">Title:    <%= image.title %></div>
                <div class="panel-body">
                  Description:    <%= image.description %>
                </div>
              </div>

              <div><%= image_tag image.image_url(:thumb).to_s %></div>
              <% if user_signed_in? %>
                  <br/>

                  <form action="/share" method="get">
                    Share to: <input class="form-control" style="width: 86%" type="text" name="email">
                    <br/>
                    <input type="hidden" name="id" value="<%= image.id %>">
                    <input type="submit" value="Share" class="btn btn-default">
                    <%= link_to 'Edit', edit_userimage_path(image), class: "btn btn-primary" %>
                    <%= link_to 'Cancel Share', cancelshare_path(image.id), class: "btn btn-danger" %>
                  </form>
              <% end %>
      <% end %>
      </div>
      <br/><br/>
      </div>
  <% end %>
  </tbody>

app/views/userimages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @userimage.title %>
</p>

<p>
  <strong>Imageversion:</strong>
  <%= @userimage.imageversion %>
</p>

<p>
  <strong>Description:</strong>
  <%= @userimage.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @userimage.image %>
</p>

<%= link_to 'Edit', edit_userimage_path(@userimage) %> |
<%= link_to 'Back', userimages_path %>

app/views/userimages/trash.html.erb
    <tbody>
    <h3 align="center">My Trash</h3>
    <p style="text-align:center" class="notice"><%= notice %></p>
    <p style="text-align:center" class="alert"><%= alert %></p>
    <% @userimages.each do |image| %>
        <div class="showBox">
          <div class="box">
            </br>
            <div class="panel panel-default" style="width: 85%">
              <div class="panel-heading">Title:    <%= image.title %></div>
              <div class="panel-body">
                Description:    <%= image.description %>
              </div>
            </div>
            <div><%= image_tag image.image_url(:thumb).to_s %></div>
            <br/>
            <% if user_signed_in? %>
                <%= link_to 'Restore', restore_path(image), class: "btn btn-primary" %>
                <%= link_to 'Delete', image, method: :delete, data: { confirm: 'Are you sure? It will delete it permanently' }, class: "btn btn-danger"%>
          <% end %>
            </div>
          <br/><br/>
    </div>
    <% end %>
    </tbody>